### ISSUE TITLE
Editor-specific builds?

### ISSUE THREAD

**Issue by aecepoglu** [eraserhd/parinfer-rust#102]
While I was packaging parinfer for Guix I realized the number of emacs crates pulled.

As a kakoune user (who realizes parinfer's ability to talk to emacs doesn't hinder its ability to talk to Kakoune) I wondered if we are able to have more minimal builds.

**Comment by eraserhd** [comment]
I definitely think the dependencies are pretty bad.  I'm working on porting this to mostly-dependency-free C as an experiment, and though I admittedly don't know much about the emacs stuff, I have to believe a plain C interface to it can't be that hard.

I don't really want to maintain separate editor builds, though.  This seems like more CI pain.

**Comment by aecepoglu** [comment]
Why not a dependency-free rust code instead of a dependency- free C code?

In which case, can you link to the effort in progress; especially if you need help with it? I don't know any rust but I used to be able to write C :)
