### ISSUE TITLE
Certain comments break parinfer

### ISSUE THREAD

**Issue by knubie** [eraserhd/parinfer-rust#106]
Hello, thanks for making this plugin!

I'm not sure if this issue belongs here or in some other more general Parinfer repo, but I've just encountered an issue where a comment seems to break Parinfer (tested on neovim 0.5). If a comment like this is found anywhere in the file:

```clj
; foo"
```

Then Parinfer will stop working.

**Comment by eraserhd** [comment]
Although this is a bit awkward, this is intentional.  See [here](https://github.com/shaunlebron/parinfer/blob/master/lib/doc/code.md#dangerous-quotes) for reasoning.

Thanks for reporting, though!
