### ISSUE TITLE
Parinfer-rust not found debug message in Kakoune

### ISSUE THREAD

**Issue by Anomalocaridid** [eraserhd/parinfer-rust#113]
When I try to use the parinfer-rust Kakoune plugin, it no longer works. Also, the following message appears in the `*debug*` buffer:

```
shell stderr: <<<
/bin/sh: line 40: exec: parinfer-rust: not found
>>>
```

My configuration for the parinfer-rust plugin in my config file is this:

```
plug "eraserhd/parinfer-rust" do %{
	cargo install --force --path .
	cargo clean
} config %{
	hook global WinSetOption filetype=(clojure|lisp|scheme|racket) %{
		parinfer-enable-window -smart
	}
}


```

**Comment by eraserhd** [comment]
It seems like parinfer-rust is not in the path.  Try cloning the repo manually and running those two "cargo" commands.  Do you get any errors?  Is parinfer-rust in the path after that?

**Comment by Anomalocaridid** [comment]
Apparently, it was in issue in my zsh config. My $PATH declaration was commented out for some reason. I thought that I checked that my $PATH wasn't changed from how I had set it, but I guess that I somehow missed it. Sorry for bothering you.

**Comment by eraserhd** [comment]
No problem!  Glad it is solved.
