### ISSUE TITLE
In kakoune, Janet `;` is treated as comment

### ISSUE THREAD

**Issue by iacore** [eraserhd/parinfer-rust#143]
In janet, `;(...)` is `(splice (...))`. I think parinfer treats it as comment instead.

I checked the file `parinfer.kak`, but that seems to work fine.
cc @andreyorst 

### Reproduction

Save the code bellow as `foo.janet`. In kak, `set buffer filetype janet`.
Try to replace `(splice parsed)` with `;parsed`.
You will see that the line turns into `(tuple) ;parsed`

```janet
(defn process-range [s]
  (def parsed (map |(scan-number $ 16) (string/split "-" s)))
  (if (= 1 (length parsed))
      (parsed 0)
      (tuple (splice parsed))))
```

**Comment by iacore** [comment]
The bug is probably because in kak, `--lang` is not passed to `parinfer-rust`

**Comment by andreyorst** [comment]
>@andreyorst can you help me on this?

Sorry, haven't used Kakoune in a year, and never used janet because of its syntax.
