### ISSUE TITLE
Mode toggle 

### ISSUE THREAD

**Issue by Gavlooth** [eraserhd/parinfer-rust#19]
Right toggling between parinfer modes does not emmit information on the current mode. 
Maybe some echoing could be added at the very least : 

function! s:toggleMode()
  if g:parinfer_mode == "smart"
    let g:parinfer_mode = "indent"
    echo "Parinfer indent mode on"
  elseif g:parinfer_mode == "indent"
    let g:parinfer_mode = "paren"
    echo "Parinfer paren mode on"
  else
    let g:parinfer_mode = "smart"
    echo "Parinfer smart mode on"
  endif
endfunction

**Comment by snoe** [comment]
nvim-parinfer.js would add the mode to the airline prompt if it existed but I'm not sure it really belonged in the plugin. I'll just leave it here if people want to add it to their rc files. smart-mode also makes mode switching much less common.
https://github.com/clojure-vim/nvim-parinfer.js/blob/master/plugin/parinfer.vim#L117-L128

**Comment by Gavlooth** [comment]
This is perfect, thanks.

**Comment by eraserhd** [comment]
My hope is that smart mode will be sufficient and nobody will need to
know.  Clearly, there's more work before that happens, though.
