### ISSUE TITLE
Hard to find, but best for vim?

### ISSUE THREAD

**Issue by timothypratley** [eraserhd/parinfer-rust#22]
This plugin appears to be the best parinfer for vim, but is not linked on the main parinfer page... instead the official link goes to an outdated plugin.

**Comment by eraserhd** [comment]
Oh, good idea.  I'll make a PR to the site.

**Comment by shaunlebron** [comment]
thanks @timothypratley, updated the links to put Rust port 2nd on list, since Atom is still best implementation right now:

http://shaunlebron.github.io/parinfer/#editor-plugins

**Comment by timothypratley** [comment]
nice :) :+1:
