### ISSUE TITLE
Block indent change messes up

### ISSUE THREAD

**Issue by lxsli** [eraserhd/parinfer-rust#23]
Given this:
```
(comment)
(deftest test-one-account
  (let [response (graphql q-one-account)]
    (is (->> response
             :body
             (= r-one-account)))))
```

I've tried `>}` and `V}>` (with cursor on `deftest`) and both result in the mangled:

```
(comment
  (deftest test-one-account)
  (let [response (graphql q-one-account)]
    (is (->> response
         :body
         (= r-one-account)))))
```

**Comment by lxsli** [comment]
Trying to `>}` on `let` in the mangled result does not end well either.

**Comment by lxsli** [comment]
Aha - I can `I  ` to shove the deftest over, bringing everything else with it. So that's a reasonable workaround but it'd be great for parinfer-rust to handle `>` better.

**Comment by eraserhd** [comment]
Hi!  Thanks for reporting.  I can't duplicate this.  If I try, `>}`, `V}>`, and even `>>` on line 2, I always get:

```
(comment
  (deftest test-one-account
    (let [response (graphql q-one-account)]
      (is (->> response
               :body
               (= r-one-account))))))
```

Can you make sure that you are on the latest version, and that the Rust library has been rebuilt?  If this still happens, what Vim version are you using?

Thanks,
-Jason

**Comment by lxsli** [comment]
Curses, that snippet also works for me in isolation. There must have been further context confusing things but I've lost it now. Sorry to waste your time.
