### ISSUE TITLE
Suggestion: add Cargo.lock file to git repository

### ISSUE THREAD

**Issue by LeOtaku** [eraserhd/parinfer-rust#24]
I think (and most Rust projects I've seen agree) it's a good idea to add the Cargo.lock file to the source code to ease potential collaborative development and aid packaging.

**Comment by eraserhd** [comment]
Will do.  I was considering this more of a library at first, and I read that it's bad to check it in for libraries, but I think now that it's just an OS library, not a Rust lib, this doesn't make sense.
