### ISSUE TITLE
Compilation error causing post-update hook to fail

### ISSUE THREAD

**Issue by daveyarwood** [eraserhd/parinfer-rust#30]
Hey, just wanted to mention this in case you weren't aware -- I was updating my vim plugins today and I noticed that the post-update hook for parinfer-rust failed.

To dig in, I went into the bundle directory and ran `cargo build --release`, and I got this compilation error:

```
$ cargo build --release
   Compiling parinfer_rust v0.2.0 (file:///home/dave/.vim/bundle/parinfer-rust)
error[E0580]: main function has wrong type
   --> src/main.rs:108:1
    |
108 | pub fn main() -> io::Result<()> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `std::result::Result`
    |
    = note: expected type `fn()`
               found type `fn() -> std::result::Result<(), std::io::Error>`

error: aborting due to previous error

error: Could not compile `parinfer_rust`.

To learn more, run the command again with --verbose.

```

**Comment by eraserhd** [comment]
@daveyarwood Interesting... This definitely compiles for me with rustc 1.28.0.  Try updating rust?

**Comment by daveyarwood** [comment]
Aha, that was definitely the problem. The latest version of Rust in the official Ubuntu PPA is currently 1.25.0. After uninstalling that package and installing the latest official release (1.29.1) from https://www.rust-lang.org/en-US/install.html, parinfer-rust compiles successfully.
