### ISSUE TITLE
[Kakoune] parinfer affects non lisp filetypes

### ISSUE THREAD

**Issue by andreyorst** [eraserhd/parinfer-rust#35]
Hi, I've finally started to use your plugin to write my lisp code, and I've noticed that it is affecting my kakrc, when I open it with kakoune:
![image](https://user-images.githubusercontent.com/19470159/49152675-99d44e00-f324-11e8-83b6-64975e891dc2.png)
The screenshot taken just after running `kak kakrc`. Maybe it's by design, and I should disable parinfer in my kakrc? I've installed it with plug.kak:
```kak
plug "eraserhd/parinfer-rust" do %{
    cargo build --release
    cargo install --force
} config %{
    hook global WinSetOption filetype=lisp %{
        hook window InsertChar   \h %{parinfer -indent}
        hook window InsertDelete \h %{parinfer -indent}
        hook window InsertChar   [\(\)\{\}\[\]] %{parinfer -indent}
        hook window InsertDelete [\(\)\{\}\[\]] %{parinfer -indent}
    }
}
```

**Comment by andreyorst** [comment]
Doublechecked, and it also happens with C, Makefile, and other files.

**Comment by eraserhd** [comment]
@andreyorst Hi, yeah I had a fix for this I forgot to push... Sorry about that.  You will likely also want to remove your window hooks when the filetype changes *from* lisp.

(I should probably just add Scheme and Lisp, though.  I'll make a note for it.)

**Comment by andreyorst** [comment]
> filetype changes from lisp

Oh, yeah, thanks. I'm just experimenting though, and still don't understand when to activate `-paren` and `-indent` modes while changing code.

**Comment by eraserhd** [comment]
`-indent` is useful if you want to manually indent on occasion.

`-smart` should happen on buffer changes.

`-paren` is good for fixing up a file that was edited by something else if it's indentation and parens don't match, assuming that the parens are correct.  It's a very good idea to run this before any `-smart` invocations, especially if you share the repo with coders who aren't so picky about indentation.

**Comment by andreyorst** [comment]
I've thought that smart is experimental. Understood, thanks again
