### ISSUE TITLE
Change comment character

### ISSUE THREAD

**Issue by rncar** [eraserhd/parinfer-rust#37]
Any way to change the comment character ?
I am using a lisp that uses # instead ; as line comment.
Would be great an option to change that.

By the way, parinfer-rust works like a charm, thanks for the project.

**Comment by eraserhd** [comment]
There is no way currently.  It doesn't seem like it would be hard to add, though.

**Comment by pepe** [comment]
Also, https://github.com/janet-lang/janet is not only using `#` for comment but `;` is a special character.

**Comment by locriacyber** [comment]
Janet + kak still has this problem, where `;` is treated as comment, not `#`.
