### ISSUE TITLE
[Kakoune] Doesn't work with tabs

### ISSUE THREAD

**Issue by ABuffSeagull** [eraserhd/parinfer-rust#38]
Is there a specific config to get tabs working?
Cause currently, even on a no-config kakoune (just `plug.kak` and this plugin), I open an empty Clojure file, press `i<tab>(a` and it keeps inserting spaces at the beginning for every character I type after the `(`.
I don't know exactly how to reproduce it, but I've also had times where it wouldn't let me de-indent with `<<`, as it would turn around and insert the spaces the instant it de-indented.
This also happens even if I change the hooks from `-smart` to `-indent` where it should not mess with the indents (if I understand it correctly).
However, if I just manually add and remove spaces myself, it all works fine.

Also, thanks for making this, I really enjoy Clojure, but I don't want to switch to Emacs :laughing:

**Comment by andreyorst** [comment]
As far as I know, it is better to use spaces with Lisp, and Parinfer works with spaces.

**Comment by eraserhd** [comment]
IIRC, the original parinfer algorithm converted tabs to spaces... though it didn't do it "correctly".  I think that's because spaces were expected (and the only things I've ever used with Lisp).

It would be nice to handle this correctly, which shouldn't be hard (but it's not a priority for me, and it'll be a month or so before I'll have time to work on parinfer-rust again).

**Comment by eraserhd** [comment]
I might actually be mis-remembering.  It's possible parinfer-rust works and the .kak needs to be updated.

**Comment by ABuffSeagull** [comment]
As a side note, I also run into the same problems even when using [smarttab](https://github.com/andreyorst/smarttab.kak) on `expandtab`. I've been messing around with the `tabstop`, `indentwidth`, `softtabstop`, and always run into problems.

**Comment by andreyorst** [comment]
> As a side note, I also run into the same problems even when using smarttab on expandtab. I've been messing around with the tabstop, indentwidth, softtabstop, and always run into problems.

I do not write lisp in Kakoune, Emacs is more natural for this task for me, but can you please send me some lisp code examples which make it work incorrectly with my smarttab plugin and parinfer-rust, so I could test this and think about possible solutions?

**Comment by ABuffSeagull** [comment]
Thanks for taking a look!
My original example still doesn't work, and doing
```clj
(defn foobar)
[]
```
then indenting the second line works (but inserts too many spaces), and you can't deindent anymore.

Although to be fair, I've not really been writing much lisp dialects anymore, so it's not super important.

**Comment by andreyorst** [comment]
I did not tested this yet, but what happens if you put your cursor before first `)` and press `RET`? The amount of indentation should be handled by parinfer-rust, and I expect it to be 2 spaces or something like that.

**Comment by ABuffSeagull** [comment]
That does work correctly, puts it on a new line in line with the `foobar`.

**Comment by ABuffSeagull** [comment]
I've gotten back into writing Clojure, and it seems like it works now!
