### ISSUE TITLE
Emacs package?

### ISSUE THREAD

**Issue by andreyorst** [eraserhd/parinfer-rust#39]
I see there's Vim and Kakoune plugins, but can parinfer-rust work with Emacs?

Development of [parinfer-mode](https://github.com/DogLooksGood/parinfer-mode) is on hold, and it doesn't provide smart mode.

Being able to use your Rust core of Parinfer with Emacs would be a jem.

**Comment by eraserhd** [comment]
@justinbarclay is working on such a thing for that reason.

**Comment by andreyorst** [comment]
Omg, thats neat!

**Comment by eraserhd** [comment]
There's a pull request in #39, but we're still sorting it out.

**Comment by eraserhd** [comment]
This is done!

**Comment by andreyorst** [comment]
Gonna give it a test!
