### ISSUE TITLE
code signature issues (was: Broken on NVIM v0.3.7)

### ISSUE THREAD

**Issue by adamneilson** [eraserhd/parinfer-rust#42]
I recently upgraded nvim to take advantage of a [recently patched vulnerability](https://arstechnica.com/information-technology/2019/06/if-you-havent-patched-vim-or-neovim-text-editors-you-really-really-should/). Unfortunately this has resulted in parinfer no longer working with this as the displayed error:

![](http://s3.amazonaws.com/screenshots.aan.io/screenshots/services.clj_Documentswefarmjuno-apisrccljjuno_apiroutes_-_NVIM_2019-06-15_15-04-45.png)

My versions look like this:

```
$ nvim --version
NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/config -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/src/nvim/auto -I/tmp/neovim-20190529-65312-1cx5evh/neovim-0.3.7/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.7/share/nvim"
```

I tried reinstalling parinfer rebuilding from scratch. The build completes without issue but again, this same error happens.

I ran `:checkhealth` and everything checks out fine. 

Any tips on what the issue may be?

Thanks in advance!

**Comment by rncar** [comment]
I am using the same nvim version and I just did PlugUpgrade and PlugUpdate, 
parinfer-rust is working fine.
```
$ nvim --version
NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.7/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by eraserhd** [comment]
@ada

**Comment by adamneilson** [comment]
I tried re-running `cargo build --release` but unfortunately the same error happens.

**Comment by eraserhd** [comment]
But the file `/Users/adam/.vimclean/bundles/parinfer-rust/target/release/libparinfer_rust.dylib` exists?  Is it executable, and does it have a file size >0?

**Comment by adamneilson** [comment]
Ah, I see where the issue is: I followed the README and installed into `~/.vimclean/bundle/parinfer-rust` which is not where it seems to expect to find the dylib in `.../bundles...` (I'm using Vundle). 

It finds it now but I'm getting an error about `code signature not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.`

This is only when I use [VimR](https://github.com/qvacua/vimr) but when running nvim directly within a terminal it works without any issue.

**Comment by eraserhd** [comment]
This sounds like Valloric/YouCompleteMe#3216

**Comment by Mqrius** [comment]
> This sounds like [ycm-core/YouCompleteMe#3216](https://github.com/ycm-core/YouCompleteMe/issues/3216)

Agreed for me. I had the same "code signature not valid" just now on built-in vim on OSX Mojave (vim 8.0). I upgraded with `brew install vim` to vim 8.1 as suggested in the linked issue, and the problem went away. I don't know if it went away due to the upgrade or due to running a vim that's in /usr/local/bin/ instead of in /usr/bin/

**Comment by shpitzs** [comment]
> Ah, I see where the issue is: I followed the README and installed into `~/.vimclean/bundle/parinfer-rust` which is not where it seems to expect to find the dylib in `.../bundles...` (I'm using Vundle).
> 
> It finds it now but I'm getting an error about `code signature not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.`
> 
> This is only when I use [VimR](https://github.com/qvacua/vimr) but when running nvim directly within a terminal it works without any issue.

@adamneilson did you find any solution / workaround to make parinfer_rust play nicely with later versions of VimR?

**Comment by adamneilson** [comment]
Unfortunately not. I've tried a variety of approaches but none successfully so I'm planning to give it one last go after upgrading to Catalina next weekend.

**Comment by eraserhd** [comment]
@adamneilson This really sucks.  Not sure how much I can help, but feel free to contact me on Clojurians slack or Freenode, GMT-5.

How did you install VimR?

**Comment by barkanido** [comment]
> Unfortunately not. I've tried a variety of approaches but none successfully so I'm planning to give it one last go after upgrading to Catalina next weekend.

@adamneilson any resort in upgrading to Catalina? Or better yet, _without upgrading_? Since my Mac is company controlled I'll have to ask them specifically to release Catalina for me before they finish testing it. Also, is that a parinfer-rust bug? An OsX bug? a MacVim bug? I am totally confused.

**Comment by eraserhd** [comment]
@barkanido My best guess is that this is a problem with VimR.  I'm not really an expert at Mac code signing, but my hunch is that the VimR distribution is somehow configured to not load unsigned code.  This "configured" might just be that it is signed itself, or that it was built with some Xcode settings.

In fact, let me start an issue on VimR.

**Comment by barkanido** [comment]
> @barkanido My best guess is that this is a problem with VimR. I'm not really an expert at Mac code signing, but my hunch is that the VimR distribution is somehow configured to not load unsigned code. This "configured" might just be that it is signed itself, or that it was built with some Xcode settings.
> 
> In fact, let me start an issue on VimR.

@eraserhd  For it also happens in macVim.

**Comment by eraserhd** [comment]
Related issue: Shougo/vimproc.vim#284

**Comment by eraserhd** [comment]
@barkanido Also, do you have the ability to change the "Allow apps downloaded from:" option in System Preferences | Security & Privacy?  Is it set to "Anywhere"?

**Comment by eraserhd** [comment]
This  is relevant: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation

**Comment by eraserhd** [comment]
https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW9

**Comment by adamneilson** [comment]
The library validation link sounds a lot like the root issue which would point to VimR needing to be fixed but it seems oddly coincidental @barkanido is also having the issue with MacVim... As s/he says, is it _a parinfer-rust bug? An OsX bug? a MacVim bug?_ I'm also totally confused.

**Comment by eraserhd** [comment]
My analysis is here:

https://github.com/eraserhd/parinfer-rust/blob/master/extra-docs/MacOS-Code-Signing.adoc

TL;DR I can reliably reproduce it, it will need to be resolved by your Vim packager, MacVim had the problem but fixed it earlier today.

I will ask VimR to fix on the issue that I opened.

**Comment by barkanido** [comment]
> @barkanido How did you install MacVim?

brew

**Comment by eraserhd** [comment]
Just brew, or brew cask?

**Comment by barkanido** [comment]
> Just brew, or brew cask?

brew cask. for me, also https://github.com/Shougo/vimproc.vim/issues/284#issuecomment-456318619 didn't work. I need an Ubuntu :-D. I am also using Vim8 behind the scenes.

**Comment by adamneilson** [comment]
> My analysis is here:
> 
> https://github.com/eraserhd/parinfer-rust/blob/master/extra-docs/MacOS-Code-Signing.adoc
> 

This is an incredible bit of research 🙌

**Comment by qvacua** [comment]
[VimR](https://github.com/qvacua/vimr) fixed this issue with the [snapshot 352](https://github.com/qvacua/vimr/releases/tag/snapshot%2F352).

**Comment by eraserhd** [comment]
Hurrah!!

**Comment by adamneilson** [comment]
Amazing! Thank you!
