### ISSUE TITLE
[Kakoune] Removing hooks maybe broken

### ISSUE THREAD

**Issue by murashitas** [eraserhd/parinfer-rust#45]
This hook introduced by 1d254e3 unintentionally removes `parinfer` hooks on `filetype=(lisp|scheme)`.

```
hook -group parinfer global WinSetOption filetype=(!clojure|lisp|scheme).* %{
    remove-hooks window parinfer
}
```

I guess there is no easy way to exclude multiple filetypes in kakoune regex, but... is this hook really necessary? It seems `parinfer` hooks only affect clojure/lisp/scheme buffer without this.

... or there's anything I’m missing?

**Comment by eraserhd** [comment]
I think the intention here is to stop parinfer processing if a buffer changes its filetype from clojure to something else... I'll look at it soon.

**Comment by murashitas** [comment]
> if a buffer changes its filetype from clojure to something else

Oops! I missed this case, it's possible. 

Anyway `(!clojure|lisp|scheme).*` matches both `lisp` and `scheme`. Hmm...

**Comment by eraserhd** [comment]
This should be fixed, thanks!

**Comment by murashitas** [comment]
@eraserhd Thanks! I confirmed ea0c292 fixes the problem.

And I'm a little bit embarrassed not realizing `(?!clojure)(?!lisp)(?!scheme).*` works...
