### ISSUE TITLE
λ symbol locks movement

### ISSUE THREAD

**Issue by andreyorst** [eraserhd/parinfer-rust#55]
Insert this code and enable parinfer:

```racket
#lang lazy

(define Y (λ(f)((λ(x)(f (x x)))(λ(x)(f (x x))))))

(define Fact
  (Y (λ(fact) (λ(x) (if (equal? x 1) 1 (* x (fact (- x 1))))))))
```
Go to first `define`, and try to move with <kbd>l</kbd> continuously. Cursor can't move beyond first `λ`. It can go backwards up or down, but not forward

**Comment by andreyorst** [comment]
It seems that any unicode symbol breaks movement:

```scheme
(define 👍 "👍")
```

Breaks plugin in the same way. Also if I try to type it in while parinfer active it looks like this:

```scheme
 (define  ~_~Q�) ;; this is (define  👍)
```
![image](https://user-images.githubusercontent.com/19470159/66822620-40c9d480-ef4d-11e9-87d2-119288fc52d6.png)

**Comment by eraserhd** [comment]
This is probably the same as #26 , which is a big deal that I should sort out.  I’ll leave it open until then, though.

**Comment by eraserhd** [comment]
Actually, I know about the cursor position part but, I don’t know about this `~_~` thing... is this a unicode entry plugin, or some kind of OS thing that you should be able to type?

**Comment by andreyorst** [comment]
> Actually, I know about the cursor position part but, I don’t know about this ~_~ thing... is this a unicode entry plugin, or some kind of OS thing that you should be able to type?

I've copied emoji and entered insert mode. Typed `(define<space><C-S-v><space>` where `C-S-v` a system shortcut to paste into terminal.

**Comment by eraserhd** [comment]
`master` now works, if you have a version of Kakoune dated today(Nov 12th) or later, having the `selections_display_column_desc` expansion and the `-display-column` option to `:select`.
