### ISSUE TITLE
Nightly needed for default build

### ISSUE THREAD

**Issue by veikman** [eraserhd/parinfer-rust#61]
Rust newbie here. I had to use `cargo +nightly build --release` with the v0.4.0 code and Rust 1.34 (in Debian 10), or else I got E0658 and the build failed. If the need for nightly is intentional for the default (non-WASM) target, I think the documentation should mention it (as it does for WASM), but perhaps I’ve just misunderstood something.

**Comment by eraserhd** [comment]
We need Rust >= 1.36, and it looks like this is what you are seeing.  It's documented in the README, but maybe not clearly?  Closing the issue, but if there's a way to communicate that more clearly, let me know.
