### ISSUE TITLE
Release a new version to fix NixOS

### ISSUE THREAD

**Issue by meatcar** [eraserhd/parinfer-rust#64]
`v0.3.1` is currently broken in NixOS, `nix-shell -p parinfer-rust` fails with the same error as #57. 

Trying to package `v0.4.0` on NixOS fails similarly, because 8b8e5ee83 is not included in it. 

Is it possible to do a new release off master, or hot-fix `v0.4.0` to include the above commit?

**Comment by eraserhd** [comment]
Thanks for mentioning this!  I've just released v0.4.2 (v0.4.1 didn't build the release properly), and made NixOS/nixpkgs#76961 .
