### ISSUE TITLE
Block comment support?

### ISSUE THREAD

**Issue by markx** [eraserhd/parinfer-rust#66]
Some Scheme dialects, like Racket, have block comments. 
Is it possible for parinfer-rust to not operate on block comments?

For example:
```Racket
#|
        (define a 1)
|#
```
will be changed to below in Indent Mode, by removing the leading whitespace.
```Racket
#|
(define a 1)
|#
```

**Comment by eraserhd** [comment]
It's a bit of work to retool parinfer-rust for other dialects, but I'm writing some Scheme now and hope to fix some things up soon.  (Also you are welcome to submit something, if you can.  :D)
