### ISSUE TITLE
Kakoune and Nixos

### ISSUE THREAD

**Issue by bhougland18** [eraserhd/parinfer-rust#67]
what do you put in the kakrc file if you are running Nixos and downloaded the parinfer-rust using the configuration.nix file?  I tried just putting the following line in my kakrc and it is giving me an error:

hook global WinSetOption filetype=(clojure|lisp|scheme|racket) %{
    parinfer-enable-window -smart
}

Sorry for the newbie question.

**Comment by eraserhd** [comment]
@bhougland18 I didn't realize this wasn't documented anywhere, so thank you for reporting this.

I just added installation instructions for kakrc+NixOS [here](https://github.com/eraserhd/parinfer-rust#nixos-or-nix-darwin).  Please let me know if I'm missing anything or could make them clearer.

**Comment by bhougland18** [comment]
The instructions are great, I didn't know Nixos had plugin options for
Kakoune.  This is even better than I hoped.  Thank you!

**Comment by bhougland18** [comment]
I added this layer and I can use it manually, but it doesn't turn on my default when I use clojure even though I have this in my kakrc:

hook global WinSetOption filetype=(clojure|lisp|scheme|racket) %{
    parinfer-enable-window -smart
}

also, when I use it manually it will only format a selection that I have highlighted.  What is the best way to have it continually run in a buffer?

**Comment by eraserhd** [comment]
This should be enough to make it work.  Some questions:

* Are there any errors in the `*debug*` buffer?
* If you `:echo %opt{filetype}<ret>` in your clojure buffer, does it say `clojure`?
* Are you sure you've restarted Kakoune (used `:kill!`)
* How are you running it manually?  (It has no facility to format only part of a buffer or only the selections - though it may look like that sometimes.)

**Comment by bhougland18** [comment]
There is an error in the *debug* buffer, it says:

error running hook WinSetOption(filetype=clojure)/: no such command: 'parinfer-enable-window'

* I verified the file is clojure by running the command you listed.
* I restarted Kakoune by using :kill!
* I tried to run it by a selection and it didn't do anything, I must have hit something that removed the brace on accident.

**Comment by bhougland18** [comment]
Parinfer works but I am still getting the error in my previous comment above in Kakoune's buffer.  Is there an easy fix for this?

**Comment by eraserhd** [comment]
I'm at a loss, honestly.  As far as I can tell, you are doing everything right.  Can you test if this happens only when you specify a Clojure file on the command-line (for a new Kakoune session)?  e.g.

```sh
kak path/to/file.clj
```

vs.

```sh
kak
:edit path/to/file.clj
```

?

I've been wondering if some of the NixOS wrappers that load plugins might load things differently.
