### ISSUE TITLE
Unexpected cursor posistion when editing multibyte text

### ISSUE THREAD

**Issue by bootleq** [eraserhd/parinfer-rust#87]
Hi, when editing multibyte text (CJK characters in my case), I found the cursor position often jumps to unexpected column.

After some study, seems the `cursorX` parinfer lib returns is virtual column, and can't be easily handled by current implementation.

Have a demo branch and working fix:
https://github.com/eraserhd/parinfer-rust/compare/master...bootleq:mbyte-setpos

I am happy to open a PR if it looks feasible, thanks.

**Comment by bootleq** [comment]
To be clarified, I should mention the issue occurs with **fullwidth** characters, not general multibyte characters.
https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by eraserhd** [comment]
I'd love a pull request!

It looks like this is a good approach, but the test case doesn't seem right -- a better test case is important.

Thanks!

**Comment by bootleq** [comment]
Confirmed solved, thank you very much.
