### ISSUE TITLE
Undo Issues :vim:

### ISSUE THREAD

**Issue by tami5** [eraserhd/parinfer-rust#93]
Hey @eraserhd, I lost the ability to undo and redo.  Basically when I edit and want to undo, I can undo two steps then the undo history becomes blank, pressing u u u go back in history but empty. Then when I try to redo it tells me `Already at newest change.`

Thanks

**Comment by hissssst** [comment]
I am experiencing exactly the same issue

**Comment by bhurlow** [comment]
seeing same

**Comment by eraserhd** [comment]
Closing, as this is definitely a duplicate of #14.

**Comment by eraserhd** [comment]
After closer inspection, this is a separate issue.   I can't reproduce on Vim 8.2.1522, but I have suspicions about what is happening.  Next time it happens, can you post VIm/Neovim, version, starting buffer contents and keystrokes to reproduce?

**Comment by agorgl** [comment]
Seeing the same issue in current neovim!
